version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    hostname: rabbitmq_host
    restart: always
    environment:
      RABBIT_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      # For AMQP protocol connected from spring boot
      - "5672:5672"
      # For web management UI
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia
volumes:
  rabbitmq_data:

