spring:
  application:
    name: device
  servlet:
    multipart:
      location: /tmp/uploads
      max-file-size: 100MB
      max-request-size: 200MB
      file-size-threshold: 10MB
cors:
  allowed-origins:
    - ${web-frontend-url}
management:
  endpoints:
    web:
      exposure:
        include: "*"
