services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    hostname: rabbitmq_host
    restart: always
    environment:
      RABBIT_DEFAULT_USER: ${RABBIT_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      # For AMQP protocol connected from spring boot
      - "5672:5672"
      # For web management UI
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia
  # kong-migrations:
  #   image: kong:3.6
  #   command: kong migrations bootstrap
  #   environment:
  #     KONG_DATABASE: postgres
  #     KONG_PG_HOST: postgres
  #     KONG_PG_DATABASE: ${POSTGRES_DB}
  #     KONG_PG_USER: ${POSTGRES_USER}
  #     KONG_PG_PASSWORD: ${POSTGRES_PASSWORD}
  #   depends_on:
  #     - postgres
  #   networks:
  #     - app-network
  # Kong DB-Backend
  # kong-gateway:
  #   image: kong:3.6
  #   container_name: kong-gateway
  #   environment:
  #     KONG_DATABASE: postgres
  #     KONG_PG_HOST: postgres
  #     KONG_PG_USER: ${POSTGRES_USER}
  #     KONG_PG_PASSWORD: ${POSTGRES_PASSWORD}
  #     KONG_PG_DATABASE: ${POSTGRES_DB}
  #     KONG_PROXY_ACCESS_LOG: /dev/stdout
  #     KONG_PROXY_ADMIN_ACCESS_LOG: /dev/stdout
  #     KONG_PROXY_ERROR_LOG: /dev/stderr
  #     KONG_ADMIN_ERROR_LOG: /dev/stderr
  #     KONG_ADMIN_LISTEN: "0.0.0.0:8001"
  #     KONG_ADMIN_GUI_URL: "http://localhost:8002"
  #     KONG_LOG_LEVEL: debug
  #     KONG_PLUGINS: bundled
  #   ports:
  #     - "8000:8000"
  #     - "8443:8443"
  #     - "8001:8001"
  #     - "8444:8444"
  #     - "8002:8002"
  #     - "8445:8445"
  #     - "8003:8003"
  #     - "8004:8004"
  #   depends_on:
  #     - kong-migrations
  #     - postgres
  #   networks:
  #     - app-network
  # Kong DB-Less
  kong-gateway:
    image: kong:3.6
    container_name: kong-gateway
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
      KONG_ADMIN_GUI_URL: "http://localhost:8002"
      KONG_LOG_LEVEL: debug
      KONG_PLUGINS: bundled
    volumes:
      - ./kong/kong.yml:/kong/kong.yml
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
      - "8002:8002"
      - "8445:8445"
      - "8003:8003"
      - "8004:8004"
    networks:
      - app-network
volumes:
  rabbitmq_data:
networks:
  app-network:
    driver: bridge
