name: Capstone Project

on:
  push:
    branches: [
      "main", "dev", 
      "feat/**", "refactor/**", 
      "style/**", "fix/**"
    ]
  pull_request:
    branches: ["dev"]

jobs:
  detect-services:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{steps.set-matrix.outputs.matrix}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Services List
        id: set-matrix
        run: |
          services=$(ls -d be/services/*/ | xargs -n 1 basename | jq -R -s -c 'split("\n")[:-1]')
          echo "matrix=$services" >> $GITHUB_OUTPUT

  bazel-build:
    runs-on: ubuntu-latest
    needs: detect-services
    strategy:
      fail-fast: false
      matrix:
        service: ${{fromJson(needs.detect-services.outputs.matrix)}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Build with Bazel
        run: bazel build //be/services/${{matrix.service}}:all

      - name: Run tests with Bazel
        run: bazel test //be/services/${{matrix.service}}:...

      - name: Upload Bazel outputs
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.service}}-bazel-bin
          path: bazel-bin/be/services/${{matrix.service}}/**/*
