name: Capstone Project

on:
  push:
    branches: [
      "main", "dev",
      "feat/**", "refactor/**",
      "style/**", "fix/**"
    ]
  pull_request:
    branches: ["dev"]

permissions:
  contents: read

jobs:
  detect-services:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{steps.set-matrix.outputs.matrix}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Gitleaks
        uses: zricethezav/gitleaks-action@v8
        with:
          # config_path: .gitleaks.toml
          verbose: true
          redacted: true
      - name: Services List
        id: set-matrix
        run: |
          services=$(ls -d be/services/*/ | xargs -n 1 basename | jq -R -s -c 'split("\n")[:-1]')
          echo "matrix=$services" >> $GITHUB_OUTPUT

  bazel-build:
    runs-on: ubuntu-latest
    needs: detect-services
    strategy:
      fail-fast: false
      matrix:
        service: ${{fromJson(needs.detect-services.outputs.matrix)}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 21

      - name: Cache Bazel
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/bazel
            ~/.cache/bazel-repo
          key: bazel-${{ runner.os }}-${{ matrix.service }}-${{ hashFiles('WORKSPACE') }}-${{ hashFiles('**/*.bzl') }}
          restore-keys: |
            bazel-${{ runner.os }}-${{ matrix.service }}

      - name: Build with Bazel
        run: bazel build //be/services/${{matrix.service}}:all

      - name: Run tests with Bazel
        run: bazel test //be/services/${{matrix.service}}/...

      - name: Upload Bazel outputs
        uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.service}}-bazel-bin
          path: bazel-bin/be/services/${{matrix.service}}/...

  android-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
        
      - name: Install JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
        
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      
      - name: Install required build-tools
        run: sdkmanager "platform-tools" "build-tools;36.0.0" "platform;android-36"

      - name: Install dependencies
        run: npm install

      - name: Grant execute permission
        run: chmod +x gradlew
        working-directory: ./fe/mobile/android

      - name: Build Debug APK
        run: ./gradlew assembleDebug
        working-directory: ./fe/mobile/android

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: ./fe/mobile/android/app/build/outputs/apk/debug/app-debug.apk

  next-build:
    name: Next.js Build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [20]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: ./fe/web/package-lock.json

      - name: Run typescheck
        run: npm run typescheck
        working-directory: ./fe/web
      
      - name: Build
        run: npm run build
        working-directory: ./fe/web

      - name: Upload production build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: ./fe/web/dist

  # qodana-analysis:
  #   runs-on: ubuntu-latest
  #   needs: [bazel-build, android-build, next-build]
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
      
  #     - name: Run Qodana
  #       uses: JetBrains/qodana-action@v2025.2
  #       with:
  #         args: --project-dir=.
  #         results-dir: qodana-results/app